cfpb/ccdb5-api

- complaint_search/decorators.py
- complaint_search/es_interface.py
- complaint_search/tests/test_views_document.py
- complaint_search/tests/test_views_search.py
- complaint_search/tests/test_views_suggest.py
- complaint_search/views.py
This PR includes code to catch any elasticsearch errors from the es_interface, and handle them gracefully with 400 errors.  This should prevent any unnecessary 500 error for the user.
- Add try/catch block for all endpoints to handle Elasticsearch Transport errors
> Catch Elasticsearch errors

- complaint_search/es_builders.py
- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
Provide license, date, count information in the API results.
- Create meta info in json by querying max_date and count info from elasticsearch
- This PR does not include adding meta info for csv, xls, and xlsx
> Add meta information

- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
Added optional parameters to ensure that Elasticsearch is able to return queries with result sets larger than the default (10,000).
> Added scrolling to ES to allow for bigger searches

- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
Right now Suggest will return a raw suggest json from elasticsearch, which include information we do not need.  Now the return values will just be a list of suggestions.
- Return list of suggestion texts when querying suggest
> Suggest should only return a list of suggestions

- complaint_search/es_builders.py
- complaint_search/es_interface.py
- complaint_search/serializer.py
- complaint_search/tests/test_serializer.py
- complaint_search/tests/test_views_search.py
- complaint_search/tests/test_views_suggest.py
- complaint_search/views.py
`no_aggs` is a new query parameter uses to indicate if we are outputting aggregations or not for JSON.
`no_aggs = True` means no aggregations will be displayed.
`no_aggs = False` means aggregations will be displayed.
`no_aggs = False` is the default value, which means that if `no_aggs` is not passed in as a query parameter, aggregations will be displayed by default.
Note that this parameter will only work for JSON format, since other formats, by default, no aggregations will be included.
- Added `no_aggs` with a default of `False` in serializer
- Added appropriate tests
- Changed some serializer fields to have default values and changed corresponding tests
> Add no_aggs parameter for JSON

- complaint_search/defaults.py
- complaint_search/es_builders.py
- complaint_search/es_interface.py
- complaint_search/serializer.py
- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_views_search.py
This PR fix issue #27.  It continues the use of scroll, but needs to scroll to the right "page" based on `frm`.  `frm` needs to be zero or a multiple of `size` to make this works.
- Added logic to scroll pages based on `frm`
- Added and fixed tests
- Pulled out default parameters to increase reusability
> Fix Pagination

- complaint_search/es_builders.py
- complaint_search/tests/expected_results/search_with_search_term_match__valid.json
- complaint_search/tests/test_es_interface.py
Query string query wasn't working as expected as it is only routing to it when keyword AND/OR/NOT/TO are in the search_term.  It should be routed if it includes more than alphanumeric and spaces.
- Only route to match if alphanumeric and/or with spaces, else route to query string query
> Query String Query - Only route to match if it is alphanumeric and/or spaces

- complaint_search/es_builders.py
- complaint_search/tests/expected_results/search_no_param__valid.json
- complaint_search/tests/expected_results/search_with_company__valid.json
- complaint_search/tests/expected_results/search_with_company_public_response__valid.json
- complaint_search/tests/expected_results/search_with_company_response__valid.json
- complaint_search/tests/expected_results/search_with_consumer_consent_provided__valid.json
- complaint_search/tests/expected_results/search_with_consumer_disputed__valid.json
- complaint_search/tests/expected_results/search_with_field__valid.json
- complaint_search/tests/expected_results/search_with_field_all__valid.json
- complaint_search/tests/expected_results/search_with_format_nonjson__valid.json
- complaint_search/tests/expected_results/search_with_frm__valid.json
- complaint_search/tests/expected_results/search_with_has_narrative__valid.json
- complaint_search/tests/expected_results/search_with_issue__valid.json
- complaint_search/tests/expected_results/search_with_max_date__valid.json
- complaint_search/tests/expected_results/search_with_min_date__valid.json
- complaint_search/tests/expected_results/search_with_product__valid.json
- complaint_search/tests/expected_results/search_with_search_term_match__valid.json
- complaint_search/tests/expected_results/search_with_search_term_qsq_and__valid.json
- complaint_search/tests/expected_results/search_with_search_term_qsq_not__valid.json
- complaint_search/tests/expected_results/search_with_search_term_qsq_or__valid.json
- complaint_search/tests/expected_results/search_with_search_term_qsq_to__valid.json
- complaint_search/tests/expected_results/search_with_size__valid.json
- complaint_search/tests/expected_results/search_with_sort__valid.json
- complaint_search/tests/expected_results/search_with_state__valid.json
- complaint_search/tests/expected_results/search_with_submitted_via__valid.json
- complaint_search/tests/expected_results/search_with_tag__valid.json
- complaint_search/tests/expected_results/search_with_timely__valid.json
- complaint_search/tests/expected_results/search_with_zip_code__valid.json
- complaint_search/tests/test_es_interface.py
Forcing highlighting for `complaint_what_happened` field no matter what field we are searching on.
- Added force highlighting on field that doesn't match search field
- If field = `_all`, highlight text from all possible fields, else the field that was specified
> Highlight text in fields that were searched

- .coveragerc
- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
- complaint_search/views.py
- requirements.txt
- Added logic to compare if `last_updated` is stale
- Added a link to CCDB_TECHNICAL_ISSUES flag to manually indicate data is invalid
- Added two items in `_meta`: 
- `is_data_stale`: check if data is older than 4 business days, true if so
- `has_data_issue`: check if CCDB_TECHNICAL_ISSUES flag has been turned on, true if so
- Made a few public functions private (with the `_`)
> 5 Business Day Notification Metdata

- complaint_search/es_builders.py
- complaint_search/tests/test_es_interface.py
This is to fix issue #39.
The reason is that the wrong field name was passed in ES when sorting.
- Use `date_received` instead of `created_date` when sorting in ES
> Issue #39: Fix sort by date

- .env_SAMPLE
- complaint_search/tests/test_views_document.py
- complaint_search/tests/test_views_search.py
- complaint_search/throttling.py
- complaint_search/views.py
This implements rate limiting for the API:
**For anonymous user**: 
Export: 2 / minute
Detail: 5 / second
Search: 20 / minute
Suggest: Unlimited
**For UI**:
Export: 6 / minute
Detail: Unlimited
Search: Unlimited
Suggest: Unlimited
- Added new rate throttle classes for each scenario
- Added corresponding tests
- A corresponding addition will also be added in the environment for cfgov-refresh so it has the correct location of the referer
> Add Rate Throttling

- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
Aggregates the `:updated_at` date of all complaints that have narratives, and then determines if the most recent date of that aggregation is older than five business days. It sets the `is_data_stale` flag in the metadata, which will trigger a warning message being displayed by CCDB5-UI
> Narrative warning

- complaint_search/es_builders.py
- complaint_search/es_interface.py
- complaint_search/tests/expected_results/search_agg_exclude__valid.json
- complaint_search/tests/expected_results/search_with_zip_code_agg_exclude__valid.json
- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_views_search.py
- complaint_search/views.py
This will remove the zip code aggregations if zip_code is not a filter.  If zip_code is a filter, it will include only aggregations for those specific filters.
- Added logic to remove zip_code if it is a filter
- Added logic to include zip_code term/filter aggregation if it is a filter
> Remove Zip Code Aggs

- complaint_search/defaults.py
- complaint_search/es_builders.py
- complaint_search/es_interface.py
- complaint_search/stream_content.py
- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_stream_content.py
- complaint_search/tests/test_views_search.py
- complaint_search/throttling.py
- complaint_search/views.py
Content from Data format plugin was originally downloaded completely before passing to the view to return as a response.  This means a large chunk of memory is being passed along this process.  To prevent stressing the server, streaming content is introduced.  The content from data format plugin is now downloaded in chunk, and an iterator is used for this purpose.  The same iterator + header is then passed to export API response directly as a streaming response.  This way we will download (from data format plugin) in a small chunk then pass the same small chunk to streaming response directly.
- Created a wrapper iterator for content that needs to have additional header to iterate over before the content (i.e. csv)
- Made the get requests to data format plugin as streaming
- Converted …
> Convert content to stream

- complaint_search/es_interface.py
- complaint_search/stream_content.py
- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_stream_content.py
- complaint_search/views.py
Data format plugin returns JSON in elasticsearch bulk format, this is not desirable format.  The format should be like a list of complaints without unnecessary information.
- Added an iterator to strip out unnecessary index json prefixed the complaint json, and added a comma to separate them, as well as the square bracket to create a list
> JSON export needs to be reformatted

- complaint_search/es_interface.py
The original format Elasticsearch returns a datetime that includes a Z to indicate timezone.  This Z creates an incorrect time when pass into other tools.  Removing the Z by giving a specific format the datetime should return as.
- Specified date format for max_date/max_narrative
> Remove last_updated timezone

- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_views_suggest_company.py
- complaint_search/views.py
Company was being passed as a filter parameter to the company type-ahead suggester. 
Because of this, once a user selected a single company no other companies were available to the suggester because they were being filtered.
This code removes the parameter if it exists, but continues to apply other field parameters so type-ahead functions similar to the surrounding filters and returns similar content.
This issue does not seem to impact the similar zip code suggester - I think this is due to the fields being returned and how they are matched but I am not 100% sure.
> Remove company param in own type-ahead suggester

- complaint_search/es_interface.py
A lot of defaults assume no time zone is UTC
For our case, the default should be Eastern Time
This is work on GHE issues/66
> Hard code max date to be noon Eastern

- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
This PR adds a work around developed this morning with @sephcoster and @rosskarchner for `requests.get` seeming not to respect the `NO_PROXY` environment variable for IP addresses. 
That `requests.get` was trying to use a proxy to reach the Elasticsearch server was causing this query to hang.
> Add a workaround for requests.get/NO_PROXY

- complaint_search/serializer.py
When a user types more than 10 characters into type-ahead the suggest API returns a 400 error "must contain less than 10 characters"
This happens for users when they select values in Company Name type-aheads. 
Steps to duplicate:
1) /data-research/consumer-complaints/search
2) Select "Company Name" from search drop-down
3) Type "BOK FINAN" and select "BOK FINANCIAL GROUP"
4) After results displayed, the search bar automatically returns "there was an issue retrieving options" which makes the user think there was a problem with their search.
Increased the number of characters allowed
> Allow more characters when suggest searching

- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
Tuned the Narrative Max aggregation to separate out narrative  max date from date and provide as metadata for each request:
- `is_narrative_stale`
- `is_data_stale`
Warnings taking effect will require CCDB5-UI pull request to be merged.
> Narrative Max Aggregations

- mkdocs.yml
- swagger-config.yaml
This is just catching up on a couple fixes I made en route to getting the docs to render.
- Gives the docs page a better title
- Removes references to deprecated excel download options
There should be no need to re-deploy docs.
> fix title of docs

- complaint_search/decorators.py
- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_view_suggest_company.py
- complaint_search/tests/test_views_document.py
- complaint_search/tests/test_views_search.py
- complaint_search/tests/test_views_suggest.py
- complaint_search/tests/test_views_suggest_company.py
- complaint_search/tests/test_views_suggest_zip.py
Work on https://github.com/cfpb/ccdb5-api/issues/74
1. Switches the error code to 424 when Elasticsearch is not available
1. When a truly unexpected condition happens (like happened 6/20-6/21), it catches the error and returns 500
1. The error details are logged, but not returned to the user
1. The default response is `{}` not `None` which can be handled by the StreamResponse
1. PEP 8 fixes (mostly whitespace)
> Improve error handling

- .coveragerc
- complaint_search/tests/test_es_interface.py
- setup.py
This PR does two things:
- Upgrade djangorestframework to 3.6.4, the latest version that supports both Django 1.8 and 1.11
- Update the coverage settings so that all application files show up in the coverage report.
- Now, the coverage report will show 100% for all files. 
- I added `pragma: no cover` to several lines that should not be run during the tests, so those lines don't reduce our test coverage stats.
(I can separate these into two different PRs if that would help)
> Upgrade djangorestframework to support Django 1.11

- complaint_search/es_interface.py
- complaint_search/export.py
- complaint_search/tests/test_export.py
- setup.py
* Adds the export script and unit tests
`export.py` script uses Django to create and export CSV and JSON files of complaint data for users. This takes the processing burden off of Elasticsearch/dataformat plugin.
https://github.cfpb.gov/data-products-team/explorer-docs/issues/460
> Export Script

- ccdb5_api/settings.py
- complaint_search/es_interface.py
- setup.py
As of https://github.com/cfpb/cfgov-refresh/pull/4641, cf.gov uses version 4.0.1 of the [django-flags](https://github.com/cfpb/django-flags) package. This package currently requires >=3.0.2,<4, and so this requirement needs to be updated to remain compatible.
There are several breaking changes in django-flags 4.0 which need to be addressed here as well:
1. Because of the way the django-flags 4.0 loads flag conditions from the database, the "flags" app must be included in Django settings `INSTALLED_APPS`. This commit modifies the test settings to do so.
2. If a flag is undefined, the flag_enabled() method now returns None instead of False. This package has some tests and logic that assume that the value is False, so this commit converts the return value to a boolean.
All unit tests pass …
> Update version of django-flags to 4.0.x

- README.md
- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
- setup.py
Test to see if the latest changes (Export script) will pass tests with a version range for `requests`. Previously this range led to Travis failures, which was why it was pinned to 2.20.1.
> Requests version

- complaint_search/es_interface.py
- complaint_search/tests/expected_results/search_with_size_corrected__valid.json
- complaint_search/tests/test_es_interface.py
- swagger-config.yaml
Enforce a maximum limit on the size parameter of 100. If the size parameter is provided to an API with a size greater than 100 it will be automatically resized to 100 to prevent DDOS attacks.
This change requires an update in the pagination logic which is captured in [this PR](https://github.com/cfpb/ccdb5-ui/pull/140)
> Size limit

- .travis.yml
- ccdb5_api/settings.py
- ccdb5_api/urls.py
- ccdb5_api/wsgi.py
- complaint_search/admin.py
- complaint_search/decorators.py
- complaint_search/defaults.py
- complaint_search/es_builders.py
- complaint_search/es_interface.py
- complaint_search/export.py
- complaint_search/models.py
- complaint_search/renderers.py
- complaint_search/serializer.py
- complaint_search/stream_content.py
- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_export.py
- complaint_search/tests/test_serializer.py
- complaint_search/tests/test_stream_content.py
- complaint_search/tests/test_view_suggest_company.py
- complaint_search/tests/test_views_document.py
- complaint_search/tests/test_views_search.py
- complaint_search/tests/test_views_suggest.py
- complaint_search/tests/test_views_suggest_company.py
- complaint_search/tests/test_views_suggest_zip.py
- complaint_search/throttling.py
- complaint_search/urls.py
- complaint_search/views.py
- setup.py
- tox.ini
There is an issue with the deep dependency, which isn't Python 3-compatible.
Still a work-in-progress. And there's linting to do.
> Make the tests pass in Python 3.6

- .travis.yml
This PR adds `--universal` to `bdist_wheel` so we have one wheel to rule all python versions.
> Update .travis.yml to build a universal wheel file

- complaint_search/export.py
This commit removes a call that sets the default string encoding used to UTF-8. This call happens when the complaint_search.export module is imported by the complaint_search.views module, which is in turn imported by the complaint_search.urls module, which is imported into cf.gov in the main cfgov-refresh urls.py.
This behavior is a little bit unexpected, because it means that the act of importing ccdb5-api URLs modifies your system default text encoding.
Also, this behavior causes [this](https://github.com/cfpb/cfgov-refresh/blob/3f2d737506e777f7816a7a74c982c2edd065d985/cfgov/v1/tests/handlers/blocks/test_feedback.py#L55) seemingly unrelated cfgov-refresh test to fail, because a "misencoded" string is now encodeable with a default string encoding.
@JeffreyMFarley suggested that this code …
> Remove call to set default encoding to UTF-8

- .gitignore
- .travis.yml
- complaint_search/export.py
- tox.ini
This change adds the linter commands (flake8/isort) to the Travis CI configuration for this project.
To get the existing linter tests to pass, it sets `lines_after_imports=2`, which feels like a reasonable setting that we already have [in cfgov-refresh](https://github.com/cfpb/cfgov-refresh/blob/3f2d737506e777f7816a7a74c982c2edd065d985/.isort.cfg#L3).
This also adds .python-version to the .gitignore so that local configuration of pyenv doesn't get tracked by git.
You can see in [the Travis build for this PR](https://travis-ci.org/chosak/ccdb5-api/builds/554769413) that the Python 3 step ran both the linter and tests, while the Python 2 step ran only the tests, as intended. Compare that with [previous builds of this project](https://travis-ci.org/cfpb/ccdb5-api/builds/548837254) where the …
> Run the linter as part of Travis testing

- complaint_search/export.py
- complaint_search/stream_content.py
- complaint_search/tests/test_export.py
- setup.py
Results containing non-ASCII characters will currently cause encoding errors when a CSV export is triggered, which causes results to be cut off prematurely.
This is due to the change in #93 that removed use of a default UTF-8 encoding.
This fix adds use of the [unicodecsv](https://pypi.org/project/unicodecsv/) Python package (already in use in cfgov-refresh) so that exports work properly when using Python 2.
A new test has been added to verify this behavior.
> Properly support Unicode in CSV exports

- complaint_search/views.py
Ensures that GET requests coming from API documentation pages controlled by the CFPB organization can access the content that they are requesting and provide full responses for users.
> Allow API requests from CFPB Github Pages

- docs/documentation/index.html
- swagger-config.yaml
Updates existing `Swagger-config.yaml` documentation to OpenAPI 3.0 specification.
If there is a desire to keep both 2.0 and 3.0 specifications in-place in the repo please let me know.
Tested locally with SwaggerUI / viewer and working.
To test the API YAML:
navigate to: https://cfpb.github.io/ccdb5-api/documentation/index.html
Update the URL at the top of the page to use: 
`https://raw.githubusercontent.com/cfpb/ccdb5-api/ff1ef1330d158b262061a9dfbddddbf42e765436/swagger-config.yaml`
This will not perform some of the changes in layout that are in the index.html, but should provide a working API call with no Format defaulted.
> Updating to OpenAPI3.0 Spec

- complaint_search/es_interface.py
This change allows us to decouple calls to Elasticsearch for hits and aggregations:
* If the `size` parameter is provided as zero (`size=0`), the request made to Elasticsearch will not return matching complaints, but it will return aggregations with any filters applied.
* If the `no_aggs` parameter is provided as True (`no_aggs=true`) then the request made to Elasticsearch will return matching complaints, but will not return aggregations
> Separate Queries

- swagger-config.yaml
Note: This PR mirrors https://github.com/cfpb/ccdb5-api/pull/110 such that the Swagger updates are made to both branches
* Specify the default behavior of `field`
* Specify the behavior of `date_received_max`
> Swagger Docs Update (dev)

- ccdb5_api/tox.py
- complaint_search/export.py
- complaint_search/tests/test_view_search_renderers.py
- complaint_search/views.py
- tox.ini
Work on #102
While it was nice getting the HTML view of a JSON endpoint, it gets in the way of the API having a simple default behavior.
When the user requests `search/api/v1/` without a format parameter, it is expected that the default format `json` is used and the content returned is of type `application/json`
However, if the request is coming from a browser, the `ACCEPT` header looks a little different
```
ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
```
The render classes would look at this string and return HTML (since it is listed before `*/*`) even though the default is 'json'
I removed the `BrowsableAPI` renderer.  This shouldn't break functionality (since it was not documented).  If users of the API enjoyed the BrowsableAPI page, …
> Remove BrowsableAPI as a renderer

- complaint_search/es_interface.py
Similarly to #106, this change allows us to decouple calls to Elasticsearch for hits and aggregations:
* If the `size` parameter is provided as zero (`size=0`), the request made to Elasticsearch will not return matching complaints, but it will return aggregations with any filters applied.
* If the `no_aggs` parameter is provided as True (`no_aggs=true`) then the request made to Elasticsearch will return matching complaints, but will not return aggregations
> Handle Size

- complaint_search/tests/test_views_search.py
- setup.py
This change will pin Django Rest Framework to >=3.9.1 to detail with a security issue that GitHub has flagged, and <4.0 which is the the exclusive maximum that Wagtail 2.8 currently pins (which we have to be compatible with when ccdb5-api gets pulled into cfgov-refresh).
There's some minor incompatibility between the previous version and more recents in terms of the way error dicts are returned. The error strings are now wrapped in `ErrorDetail`. This change also updates the tests as appropriate.
> Pin Django Rest Framework to >=3.9.1,<4.0

- complaint_search/es_builders.py
- complaint_search/tests/expected_results/search_with_tags__valid.json
- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_views_search.py
- tox.ini
1. https://www.consumerfinance.gov/data-research/consumer-complaints/search/?from=0&searchField=all&searchText=&size=25&sort=created_date_desc&tags=Older%20American&tags=Servicemember
1. When a user selects two values from the "Tags" filter, 0 results are shown instead of the sum of their results.
We changed how we index the tags filter, but we did not change the API, which treated them as boolean fields
Pass with updated criteria
> Fix "Tags" filter shows 0 results when two tags are selected

- README.md
- setup.py
Change version of `django-localflavor` to support version 3.0
This change will resolve the following in `cfgov-refresh`:
`ERROR: ccdb5-api 1.7.0 has requirement django-localflavor<3,>=1.1, but you'll have django-localflavor 3.0 which is incompatible.`
- Include `djangolocalflavor` in `README.md`
- Update version of `django-localflavor` to support 3.0 in `setup.py`
1. tox -e lint
2. tox -e py36-dj111
3. tox -e py36-dj22
> Update django-localflavor to 3.0

- swagger-config.yaml
Closes #122 
The use of the `field` parameter is [here](https://github.com/cfpb/ccdb5-api/blob/master/complaint_search/es_builders.py#L216-L244)
> Change the description of the "field" parameter

- setup.py
This package is no longer used in ccdb5.
> Remove unicodecsv from setup.py

- complaint_search/es_builders.py
This change ensures that any user supplied product and issue filters are applied to the `States` aggregation returned by the `/states/` API.
> States Aggregation filter

- complaint_search/es_builders.py
- complaint_search/es_interface.py
- complaint_search/serializer.py
- complaint_search/tests/expected_results/trends_company_filter__valid.json
- complaint_search/tests/test_es_interface_trends.py
- complaint_search/views.py
- swagger-config.yaml
* Standardized "collections" to properly be "tags"
* Added the ability to receive a company aggregation if one or more company filters is supplied
* Added functionality to exclude aggregations by default to prevent unnecessary network traffic
* Unit tests for both functionalities
* Updated Swagger
> Company Aggregation and Exclude Aggregations

- complaint_search/defaults.py
- complaint_search/es_builders.py
- complaint_search/serializer.py
- complaint_search/tests/expected_results/trends_issue_focus__valid.json
- complaint_search/tests/expected_results/trends_issue_focus_company_filter__valid.json
- complaint_search/tests/test_es_interface_trends.py
- complaint_search/views.py
Rather than providing a sub lens through which to view the trends aggregations, this PR adds the Focus functionality which facilitates lens filtering by a single provided item (eg, a particular product or issue).
Features:
* `/trends/` endpoint now accepts `focus` as a param
* Aggregations are filtered based on the focus provided
Fixes:
* Fixed an issue where the `company` filter was being incorrectly applied to `/states/`
> Trends Focus

- complaint_search/es_builders.py
In order to provide the most detailed complaint counts on the map screen, the `/states/` endpoint should return the states aggregation without applying the states filters to it. This prevents all other states from being zeroed out when a state filter is selected.
> Don't apply state filter to /states/ aggregation

- .coveragerc
- ccdb5_api/settings.py
- complaint_search/es_interface.py
- complaint_search/tests/es_interface_test_helpers.py
- complaint_search/tests/expected_results/search_with_size_corrected__valid.json
- complaint_search/tests/expected_results/states_agg__valid.json
- complaint_search/tests/expected_results/states_date_filters__valid.json
- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_es_interface_states.py
In my `event_tag` branch and in `dev`, the tests have been refactored so that the coverage shows 100%.  It would be nice to have that in `master` especially with some hotfixes upcoming
These commits were `cherry-pick`ed from `dev`
* 58e81cb
* 30d3483
* 268f7b6
> Cherry Pick the Test Refactor

- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
- setup.py
- tox.ini
Currently, the company type-ahead only picks up the first letter/words. If users type partial word that happens to be in the middle of the name, the type-ahead doesn't pick up. For example, trying to search for 'Chase', will find 0 results since the company name is 'JP Morgan Chase'
This PR uses `wildcard` instead of `prefix` to search:
- `issue` (will find "Mortgage" in "Closing on a mortgage")
- `state` (will find "Jersey" in "New Jersey")
- `company` (satisfies the use case)
The code will still use `prefix` for zip codes since there are a lot of zip codes and they are rarely searched for in the middle. ('210' would not expect to return '90210')
> Switch suggesters to "contains" rather than "starts with"

- complaint_search/es_builders.py
- complaint_search/tests/expected_results/search_with_has_narrative__valid.json
The `has_narrative` parameter got left out of aggregation filters when the filtering was refactored (due to `has_narrative` having some special logic for converting strings to bools). This PR adds back `has_narrative` as a filter option for aggregations.
> Narrative bugfix

- complaint_search/es_builders.py
- complaint_search/tests/expected_results/search_with_company__valid.json
- complaint_search/tests/expected_results/search_with_company_agg_exclude__valid.json
- complaint_search/tests/expected_results/search_with_zip_code__valid.json
- complaint_search/tests/expected_results/search_with_zip_code_agg_exclude__valid.json
Currently, when a user adds a Company or ZIP Code, it is not staying in the left-hand filter.
Acceptance Criteria:
* Any filter added by a user should stay checked on the left-hand side under the appropriate filter heading.
> Include aggregation if it is used as a filter

- swagger-config.yaml
- Removing the `ly` suffix not used in `trend_interval` parameters.
- Added suggested filter parameters for `day` interval parameter to description
> Updating interval params in API docs

- README.md
Noticed you all had made the swap to github actions, but had a the old travis badge in the README.
> Swap Travis Badge with Github Actions Badge

- README.md
- setup.py
- tox.ini
This change updates our supported version range to the LTS release of Django (2.2) and the current release of Django (3.1).
- Added support for Django 3.1
- tox
> Support LTS + Current versions of Django

- swagger-config.yaml
Closes #162.
Fixes typo, and adds the Focus parameter to the swagger documentation.
> Fixed Typo, Added Focus Parameter

- ccdb5_api/settings.py
We've removed CSRF from non-authenticated paths in https://github.com/cfpb/consumerfinance.gov/pull/6366. The PR removes the CSRF middleware from the standalone testing settings.
> Remove CSRF middleware in settings

- complaint_search/tests/test_views_document.py
- complaint_search/tests/test_views_search.py
- complaint_search/throttling.py
Integration testing with Cypress is difficult when testing on a server, because many of the
test actions generate API calls that violate throttling rules, and the tests have to be
slowed down to work.
This change allows throttling to be sidestepped when DEBUG is True, which can be set
locally and on servers where CI testing could be run.
DEBUG Is always False in production, but we don't want to be doing Cypress testing there.
> Sidestep API throttling when in DEBUG mode

- complaint_search/es_interface.py
- complaint_search/tests/expected_results/states_agg__valid.json
- complaint_search/tests/expected_results/states_date_filters__valid.json
- complaint_search/tests/test_views_search.py
A test `size` value was errantly left in the es_interface.states_agg function.
The map tab does not need any hits, so size should be 0 for efficiency.
> Remove unneeded hits from map-tab requests

- complaint_search/decorators.py
- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_es_interface_states.py
- complaint_search/tests/test_es_interface_trends.py
- complaint_search/tests/test_view_suggest_company.py
- complaint_search/tests/test_views_document.py
- complaint_search/tests/test_views_search.py
- complaint_search/tests/test_views_suggest.py
- complaint_search/tests/test_views_suggest_company.py
- complaint_search/tests/test_views_suggest_zip.py
- setup.py
Now that consumerfinance.gov is done with the elasticsearch7 custom package,
we can import `elasticsearch` everywhere, and we'll all be on the latest
version that works with our AWS Elasticsearch services – 7.10.1.
This will not change the version of the package we're using. It only drops the custom build of that version, 
which had allowed us to run ES2 and ES7 side-by-side.
> Convert custom elasticsearch7 imports to elasticsearch

- complaint_search/views.py
The cache tag "complaints" has been added to other search pages; this adds it
to API responses so that cache invalidation by cache tag will purge cached API calls.
> Add a complaints cache tag to the api views

- complaint_search/defaults.py
- complaint_search/es_interface.py
- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_get_pagination_query_size.py
- tox.ini
This change sets the default initial pagination depth to 200 for
fast initial searches, but allows users to explore as deeply as they
dare by progressively increasing the pagination depth by another
100 hits, as needed, up to 10K.
Searches will lose tiny amounts of speed as pagination goes deeper,
maxing out at around 6 seconds per "next page" request when a theoretical user
approaches 10,000 hits under the sea.
You can test the deep pagination locally if you have a local complaint index
populated. But it's much simpler to test on DEV4, where it has been deployed and tested.  
CA has signed off on its testing there.
> Allow efficient deep pagination to 10K hits

- .flake8
- setup.py
- tox.ini
"tox -e lint" was failing on this repository. There were multiple conflicting configurations for flake8 in .flake8 and tox.ini.
This commit simplifies so that the configuration only lives in .flake8, and works again even on the latest version of flake8.
See also https://github.com/cfpb/wagtail-inventory/pull/61 and https://github.com/cfpb/wagtail-sharing/pull/58.
> Fix flake8 configuration

- ccdb5_api/urls.py
- complaint_search/urls.py
- setup.py
- tox.ini
This commit removes support for versions of Django before 3.2. This allows for removal of several try/except ImportError clauses and migration away from the deprecated `url` method in favor of `re_path`. This fixes the following Django deprecation warning:
> RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
Note that the linter CI check will fail on this PR; a separate fix for that is in #195.
> Deprecate Django support before version 3.2

- .github/workflows/release.yml
We use Python 3.8 to run CI testing for this repository, so we should use it to build release packages as well. Additionally building releases with 3.6 no longer works:
https://github.com/cfpb/ccdb5-api/actions/runs/4056429229
> Use Python 3.8 to build releases

- complaint_search/tests/test_es_interface.py
- complaint_search/tests/test_es_interface_states.py
- complaint_search/tests/test_es_interface_trends.py
- complaint_search/tests/test_view_search_renderers.py
- complaint_search/tests/test_view_suggest_company.py
- complaint_search/tests/test_views_document.py
- complaint_search/tests/test_views_search.py
- complaint_search/tests/test_views_states.py
- complaint_search/tests/test_views_suggest.py
- complaint_search/tests/test_views_suggest_company.py
- complaint_search/tests/test_views_suggest_zip.py
- complaint_search/tests/test_views_trends.py
- setup.py
- tox.ini
This PR updates this app's dependencies and adds support for Django 4.2.
> Update dependencies and support Django 4.2

- docs_requirements.txt
- requirements.txt
- setup.py
- tox.ini
The CCDB API requirements had been neglected for some time. This PR brings dependencies up to date with the host cfgov framework, and restores the tox tests, which now pass.
Added files;
reqirements.txt file for local development and testing.
Note:
The API is limited to Python 3.8 because of restrictions on the current cfgov deployment environment. That also affects which version of Django we can use (can't move to Django 5).
We'll want to run this on a dev server to confirm.
> DATAP-1733: Update packages and tests

- .github/workflows/release.yml
We have to stay even with the Python version used in cfgov, since we deploy inside that project. cfgov is pinned at 3.8 at present because of deployment infrastructure. But 3.8 is no longer available as an import, and our release fails to build a wheel.
The new script code mirrors how cfgov configures its releases to download 3.8.
> Update the release action to download Python 3.8

- complaint_search/es_interface.py
The current implementation doesn't properly pass username/password credentials when connecting to Elasticsearch using HTTP (as opposed to connecting with AWS credentials).
The version 7.x Python elasticsearch library doesn't support the http_auth parameter currently specified, see code [here](https://github.com/elastic/elasticsearch-py/blob/e275834941ea053c300e2c4bc494fccd5265f127/elasticsearch/client/__init__.py#L63).
Instead, the username/password must be passed as part of the HTTP hostname. Additionally, the `use_ssl` parameter needs to be set if connecting via HTTPS.
To test, try connecting to an ES server using ES_HOST/ES_PORT both with and without ES_USER/ES_PASSWORD. I've confirmed this on our infrastructure.
See internal DEVPLAT-1569 for additional context, and …
> Fix use of HTTP credentials

- .github/workflows/release.yml
The GitHub Action that builds wheels on releases has been broken for some time due to Python 3.8's EOL, see for example https://github.com/cfpb/ccdb5-api/actions/runs/17275449040
This commit updates the release building code to use a more modern version of Python (3.13) - we don't need to use the runtime version of Python (3.8) to build the wheel.
It also updates the action to run on pull requests to ensure that the release package can be built (without actually doing the upload).
> Fix release wheel builds/uploads
