.env_SAMPLE, README.md, setup.py
This was moved from my personal repository, this is to fix some invalid references to the old repository.
- Changed reference to `complaint-search` to `ccdb5-api`
- Pointed reference back to this repository
@JeffreyMFarley @AdamZarger
=> Correct Name Information

complaint_search/es_interface.py, complaint_search/tests/test_es_interface.py
When creating the bool should clause, product and issue needs to be raw in order to do the searching.
- Changed the use of raw for product, sub-product, issue, sub-issue
@AdamZarger @JeffreyMFarley 
cc
@sephcoster
=> Search for Raw for Product and Issue

.gitignore, complaint_search/tests/test_views_search.py, complaint_search/views.py
=> Add CORS support when in development/debug mode

complaint_search/es_builders.py, complaint_search/serializer.py, complaint_search/tests/expected_results/search_no_param__valid.json, complaint_search/tests/expected_results/search_with_company__valid.json, complaint_search/tests/expected_results/search_with_company_public_response__valid.json, complaint_search/tests/expected_results/search_with_company_response__valid.json, complaint_search/tests/expected_results/search_with_consumer_consent_provided__valid.json, complaint_search/tests/expected_results/search_with_consumer_disputed__valid.json, complaint_search/tests/expected_results/search_with_field__valid.json, complaint_search/tests/expected_results/search_with_frm__valid.json, complaint_search/tests/expected_results/search_with_has_narratives__valid.json, complaint_search/tests/expected_results/search_with_issue__valid.json, complaint_search/tests/expected_results/search_with_max_date__valid.json, complaint_search/tests/expected_results/search_with_min_date__valid.json, complaint_search/tests/expected_results/search_with_product__valid.json, complaint_search/tests/expected_results/search_with_search_term__valid.json, complaint_search/tests/expected_results/search_with_size__valid.json, complaint_search/tests/expected_results/search_with_sort__valid.json, complaint_search/tests/expected_results/search_with_state__valid.json, complaint_search/tests/expected_results/search_with_submitted_via__valid.json, complaint_search/tests/expected_results/search_with_tag__valid.json, complaint_search/tests/expected_results/search_with_timely__valid.json, complaint_search/tests/expected_results/search_with_zip_code__valid.json, complaint_search/tests/test_views_search.py
This PR fixes two issues here:
- State in aggregations were cut off https://github.com/cfpb/ccdb5-api/issues/16
- Now all aggregations do not have a size limit, and will not be cut off.
- Zip code was not filtering
- Now zip code is filtering, and more tests have been added to check the behaviors for all fields
@JeffreyMFarley
=> issues with states and zip codes

complaint_search/views.py
The development version of the UI requires the CORS headers
=> Add CORS support on suggest endpoint

complaint_search/views.py
Also, created a function to avoid copy pasta
=> Add CORS support for document endpoint

complaint_search/defaults.py, complaint_search/es_builders.py, complaint_search/es_interface.py, complaint_search/serializer.py, complaint_search/tests/test_es_interface.py, complaint_search/tests/test_views_search.py
This is the same as #29, since it was closed due to merge order with #30.
=> Reapply pagination changes

complaint_search/defaults.py, complaint_search/es_builders.py, complaint_search/serializer.py, complaint_search/tests/expected_results/search_no_highlight__valid.json, complaint_search/tests/test_es_interface.py, complaint_search/tests/test_serializer.py, complaint_search/tests/test_views_search.py, complaint_search/views.py
`no_highlight` is default to `False` if not specified, when it is `True`, it means that highlighting will not be included in the result
- Add `no_highlight` support and add corresponding tests
=> Add no_highlight parameter

.travis.yml, setup.py
See https://github.com/cfpb/eregs-2.0/pull/68
=> Configure travis to build wheels

complaint_search/es_builders.py, complaint_search/es_interface.py, complaint_search/serializer.py, complaint_search/tests/test_es_interface.py, complaint_search/tests/test_views_suggest_zip.py, complaint_search/urls.py, complaint_search/views.py
Added a suggest endpoint for handling zip codes
Testing = 💯 
Also made some PEP8 changes, sorry for the check-in noise but my IDE complains when the Python isn't correct
=> Suggest Zip Code

complaint_search/es_interface.py, complaint_search/tests/expected_results/search_with_company_agg_exclude__valid.json, complaint_search/tests/test_es_interface.py, complaint_search/tests/test_view_suggest_company.py, complaint_search/tests/test_views_search.py, complaint_search/urls.py, complaint_search/views.py
- Added suggest_company endpoint, which is similar to how suggest_zip is
- Added logic to remove company from agg if not filtered
- Refactor to reuse logic from suggest_zip
=> Add suggest_company endpoint

complaint_search/es_builders.py, complaint_search/tests/expected_results/search_with_issue__valid.json, complaint_search/tests/expected_results/search_with_product__valid.json, complaint_search/tests/test_es_interface.py
Now filters will respond with appropriate counts if sub-elements are not mutually exclusive to other parent elements.
=>  Nested Boolean for Parent / Child Filters

complaint_search/swagger.yml, complaint_search/tests/test_views_document.py, complaint_search/tests/test_views_swagger.py, complaint_search/urls.py, complaint_search/views.py
1. Copy the text from `swagger.yml`
1. Navigate to https://editor.swagger.io/
1. Clear the current contents
1. Paste the copied text
1. Profit!
1. `python manage.py runserver`
1. Navigate to http://localhost:8000/docs/
1. Load that bad boy up
1. Navigate to http://localhost:8000/data-research/consumer-complaints/search/api/v1/docs
=> Provide API documentation

complaint_search/es_interface.py, complaint_search/export_csv.py, complaint_search/tests/test_es_interface.py, setup.py
Added an `export_csv.py` script and updated `es_interface.py` to call script when user exports a CSV of complaints. Intended for temporary testing
=> Exporting CSV testing

complaint_search/export.py
5K limit was added inadvertently. Users should be able to download all complaints from their export.
=> Reverting 5k limit to Unlimited

swagger-config.yaml
The current version can be seen here: https://cfpb.github.io/ccdb5-api/documentation/index.html
It will be updated when this PR is merged
=> Fix a few errors in the Swagger doc

complaint_search/es_builders.py, complaint_search/es_interface.py, complaint_search/tests/test_es_interface.py, complaint_search/tests/test_views_states.py, complaint_search/urls.py, complaint_search/views.py
This is a new endpoint `/states/` that:
* Queries all complaints, filtering by user-chosen filters
* Aggregates the results into:
* All States (ordered by descending complaint count)
* Top 5 Products
* Top 5 Issues
=> States API

swagger-config.yaml
The updates reflect the interface as currently developed in `dev`
=> Update Swagger documentation

ccdb5_api/settings.py, requirements.txt, setup.py
There seems to have been a package change that breaks the build, this will fix it
=> Fix broken Travis builds

swagger-config.yaml
* Specify the default behavior of `field`
* Specify the behavior of `date_received_max`
* Removed unnecessary quotation marks
* Fixed minor typos
=> Swagger Docs Update

complaint_search/es_builders.py
When a particular state is applied as a filter to the `/geo/states/` API call, it was applying that state as a filter and causing all other states in the map to show a count of zero. In order to prevent this case, state filters will not be applied to the state aggregation when calling `/geo/states/`
=> /geo/states/ filters

complaint_search/es_builders.py, complaint_search/tests/expected_results/search_with_tags__valid.json, complaint_search/tests/test_es_interface.py, complaint_search/tests/test_views_search.py
https://github.com/cfpb/ccdb5-api/pull/120 fixed an issue with the Tags filter in production.  This PR applies the same fix to `dev`
=> Apply the `master` Tags fix to `dev`

complaint_search/es_builders.py, complaint_search/es_interface.py, complaint_search/serializer.py, complaint_search/tests/es_interface_test_helpers.py, complaint_search/tests/expected_results/trends_default_params__valid.json, complaint_search/tests/expected_results/trends_exclude_and_date_filters__valid.json, complaint_search/tests/expected_results/trends_filter__valid.json, complaint_search/tests/expected_results/trends_sub_lens_product__valid.json, complaint_search/tests/expected_results/trends_top_self_filter__valid.json, complaint_search/tests/test_es_interface.py, complaint_search/tests/test_es_interface_trends.py, complaint_search/tests/test_views_trends.py, complaint_search/urls.py, complaint_search/views.py, swagger-config.yaml
This PR introduces the first iteration of the `/trends/` API. This API will supply consumer complaint data aggregated in such a way to support the data and charts in the Trends tab.
=> Trends API

complaint_search/es_builders.py, complaint_search/tests/expected_results/search_with_date_received_max__valid.json, complaint_search/tests/expected_results/search_with_date_received_min__valid.json, complaint_search/tests/expected_results/states_date_filters__valid.json
Fixed the date filter mapping to map to the correct field name when filtering by date in the Elasticsearch request.
=> Fix date filter mapping

complaint_search/es_builders.py, complaint_search/tests/expected_results/states_agg__valid.json, complaint_search/tests/expected_results/states_date_filters__valid.json
Add sub-aggregations for sub products and sub issues to promote consistency between charts
=> State sub-aggregations

complaint_search/es_builders.py, complaint_search/tests/expected_results/search_with_company_public_response__valid.json, complaint_search/tests/expected_results/search_with_company_response__valid.json, complaint_search/tests/expected_results/search_with_consumer_consent_provided__valid.json, complaint_search/tests/expected_results/search_with_issue__valid.json, complaint_search/tests/expected_results/search_with_product__valid.json, complaint_search/tests/expected_results/search_with_state__valid.json, complaint_search/tests/expected_results/search_with_submitted_via__valid.json, complaint_search/tests/expected_results/search_with_tags__valid.json, complaint_search/tests/expected_results/search_with_timely__valid.json
Add back the logic that prevents the Aggregation Builder from applying filters to themselves.
=> Aggregation Self Filters

complaint_search/es_interface.py
This change fixes a bug with export requests made directly to the API that included the `no_highlight` parameter.
=> Export format fix

setup.py, tox.ini
=> Switch Django 3.1 to 3.2 for testing

.github/workflows/ci.yml, tox.ini
This change updates our base Python required to 3.8.
=> Update to Python 3.8

.github/workflows/release.yml
Reverts cfpb/ccdb5-api#213
did not work. will need another solution.
=> Revert "Update the release action to download Python 3.8"
